export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  VERIFY_LOGIN_OTP: '/verify-login',
  VERIFY_SIGNUP_OTP: '/verify-signup',
  REGISTER_BUSINESS: '/register-business',
  DASHBOARD: '/dashboard',
  CLIENTS: '/clients',
  INVITE_CLIENT: '/clients/invite',
  CLIENT_DETAIL: '/clients/:id',
  EDIT_CLIENT: '/clients/:id/edit',
  LIBRARY: '/library',
  EXERCISES: '/library/exercises',
  EXERCISE_DETAIL: '/library/exercises/:id',
  FOODS: '/library/foods',
  FOOD_DETAIL: '/library/foods/:id',
  RECIPES: '/library/recipes',
  RECIPE_DETAIL: '/library/recipes/:id',
  NUTRITION_PLANS: '/library/nutrition-plans',
  NUTRITION_PLAN_DETAIL: '/library/nutrition-plans/:id',
  TRAINING_PLANS: '/library/training-plans',
  TRAINING_PLAN_DETAIL: '/library/training-plans/:id',
  SETTINGS: '/settings',
} as const;
