import Config

# Configure your database
config :easy, Easy.Repo,
  username: "admin",
  password: "L2KjxOH9al",
  hostname: "localhost",
  database: "xobizz_admin",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :easy, EasyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "SvVJCnupjkXWkSeEBgMdkpfl/BhoaQuySnbgbIZIEXsVfvv9YrA6PJLzUl+xYwJ1",
  watchers: []

# CoachApp endpoint configuration
config :easy, CoachApp.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 4001],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "HT6LHHL/kSeEBgMdkpfl/BhoaQuySnbgbIZIEXsVfvv9YrA6PJLzUl+xYwJ1COACH",
  watchers: []

# ClientApp endpoint configuration (if needed later)
# config :easy, ClientApp.Endpoint,
#   http: [ip: {127, 0, 0, 1}, port: 4002],
#   check_origin: false,
#   code_reloader: true,
#   debug_errors: true,
#   secret_key_base: "CLIENT123456789",
#   watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :easy, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Authentication and JWT configuration
config :easy, Easy.Accounts.Token,
  secret_key: "dev-jwt-secret-key-should-be-changed-in-production"

config :joken, default_signer: "dev-jwt-secret-key-should-be-changed-in-production"

config :easy, Easy.Accounts.OTP, dev_otp: "123456"

# CORS configuration for development
config :cors_plug,
  origin: ["*"],
  credentials: true
