/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestAuthRouteImport } from './routes/_guest/_auth'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedPageRouteImport } from './routes/_authed/page'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedLibraryIndexRouteImport } from './routes/_authed/library/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedClientsIdRouteImport } from './routes/_authed/clients/$id'
import { Route as GuestAuthRegisterIndexRouteImport } from './routes/_guest/_auth/register/index'
import { Route as GuestAuthLoginIndexRouteImport } from './routes/_guest/_auth/login/index'
import { Route as GuestAuthRegisterVerifyRouteImport } from './routes/_guest/_auth/register/verify'
import { Route as GuestAuthLoginVerifyRouteImport } from './routes/_guest/_auth/login/verify'
import { Route as AuthedLibraryTrainingPlansNewRouteImport } from './routes/_authed/library/training-plans/new'
import { Route as AuthedLibraryRecipesNewRouteImport } from './routes/_authed/library/recipes/new'
import { Route as AuthedLibraryNutritionPlansNewRouteImport } from './routes/_authed/library/nutrition-plans/new'
import { Route as AuthedLibraryFoodsNewRouteImport } from './routes/_authed/library/foods/new'
import { Route as AuthedLibraryExercisesNewRouteImport } from './routes/_authed/library/exercises/new'
import { Route as AuthedLibraryTrainingPlansIdEditRouteImport } from './routes/_authed/library/training-plans/$id/edit'
import { Route as AuthedLibraryRecipesIdEditRouteImport } from './routes/_authed/library/recipes/$id/edit'
import { Route as AuthedLibraryNutritionPlansIdEditRouteImport } from './routes/_authed/library/nutrition-plans/$id/edit'
import { Route as AuthedLibraryFoodsIdEditRouteImport } from './routes/_authed/library/foods/$id/edit'
import { Route as AuthedLibraryExercisesIdEditRouteImport } from './routes/_authed/library/exercises/$id/edit'
import { Route as AuthedLibraryTrainingPlansIdBuilderIndexRouteImport } from './routes/_authed/library/training-plans/$id/builder/index'
import { Route as AuthedLibraryNutritionPlansIdBuilderIndexRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/index'
import { Route as AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRouteImport } from './routes/_authed/library/training-plans/$id/builder/workouts/$workoutId/index'
import { Route as AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/days/$day/index'
import { Route as AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/meals/$mealId/edit'
import { Route as AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/assignments/$planItemId/edit'
import { Route as AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRouteImport } from './routes/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId'
import { Route as AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId'
import { Route as AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/days/$day/meals/new'
import { Route as AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRouteImport } from './routes/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/index'
import { Route as AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/index'
import { Route as AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRouteImport } from './routes/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId'
import { Route as AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRouteImport } from './routes/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthRoute = GuestAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => GuestRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPageRoute = AuthedPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLibraryIndexRoute = AuthedLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsIdRoute = AuthedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestAuthRegisterIndexRoute = GuestAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => GuestAuthRoute,
} as any)
const GuestAuthLoginIndexRoute = GuestAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => GuestAuthRoute,
} as any)
const GuestAuthRegisterVerifyRoute = GuestAuthRegisterVerifyRouteImport.update({
  id: '/register/verify',
  path: '/register/verify',
  getParentRoute: () => GuestAuthRoute,
} as any)
const GuestAuthLoginVerifyRoute = GuestAuthLoginVerifyRouteImport.update({
  id: '/login/verify',
  path: '/login/verify',
  getParentRoute: () => GuestAuthRoute,
} as any)
const AuthedLibraryTrainingPlansNewRoute =
  AuthedLibraryTrainingPlansNewRouteImport.update({
    id: '/library/training-plans/new',
    path: '/library/training-plans/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryRecipesNewRoute = AuthedLibraryRecipesNewRouteImport.update({
  id: '/library/recipes/new',
  path: '/library/recipes/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLibraryNutritionPlansNewRoute =
  AuthedLibraryNutritionPlansNewRouteImport.update({
    id: '/library/nutrition-plans/new',
    path: '/library/nutrition-plans/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryFoodsNewRoute = AuthedLibraryFoodsNewRouteImport.update({
  id: '/library/foods/new',
  path: '/library/foods/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLibraryExercisesNewRoute =
  AuthedLibraryExercisesNewRouteImport.update({
    id: '/library/exercises/new',
    path: '/library/exercises/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryTrainingPlansIdEditRoute =
  AuthedLibraryTrainingPlansIdEditRouteImport.update({
    id: '/library/training-plans/$id/edit',
    path: '/library/training-plans/$id/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryRecipesIdEditRoute =
  AuthedLibraryRecipesIdEditRouteImport.update({
    id: '/library/recipes/$id/edit',
    path: '/library/recipes/$id/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryNutritionPlansIdEditRoute =
  AuthedLibraryNutritionPlansIdEditRouteImport.update({
    id: '/library/nutrition-plans/$id/edit',
    path: '/library/nutrition-plans/$id/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryFoodsIdEditRoute =
  AuthedLibraryFoodsIdEditRouteImport.update({
    id: '/library/foods/$id/edit',
    path: '/library/foods/$id/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryExercisesIdEditRoute =
  AuthedLibraryExercisesIdEditRouteImport.update({
    id: '/library/exercises/$id/edit',
    path: '/library/exercises/$id/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryTrainingPlansIdBuilderIndexRoute =
  AuthedLibraryTrainingPlansIdBuilderIndexRouteImport.update({
    id: '/library/training-plans/$id/builder/',
    path: '/library/training-plans/$id/builder/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryNutritionPlansIdBuilderIndexRoute =
  AuthedLibraryNutritionPlansIdBuilderIndexRouteImport.update({
    id: '/library/nutrition-plans/$id/builder/',
    path: '/library/nutrition-plans/$id/builder/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute =
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRouteImport.update({
    id: '/library/training-plans/$id/builder/workouts/$workoutId/',
    path: '/library/training-plans/$id/builder/workouts/$workoutId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute =
  AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRouteImport.update({
    id: '/library/nutrition-plans/$id/builder/days/$day/',
    path: '/library/nutrition-plans/$id/builder/days/$day/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute =
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRouteImport.update({
    id: '/library/nutrition-plans/$id/builder/meals/$mealId/edit',
    path: '/library/nutrition-plans/$id/builder/meals/$mealId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute =
  AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRouteImport.update(
    {
      id: '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit',
      path: '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit',
      getParentRoute: () => AuthedRoute,
    } as any,
  )
const AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute =
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRouteImport.update(
    {
      id: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId',
      path: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId',
      getParentRoute: () => AuthedRoute,
    } as any,
  )
const AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute =
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRouteImport.update({
    id: '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId',
    path: '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute =
  AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRouteImport.update({
    id: '/library/nutrition-plans/$id/builder/days/$day/meals/new',
    path: '/library/nutrition-plans/$id/builder/days/$day/meals/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute =
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRouteImport.update(
    {
      id: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/',
      path: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/',
      getParentRoute: () => AuthedRoute,
    } as any,
  )
const AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute =
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRouteImport.update(
    {
      id: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/',
      path: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/',
      getParentRoute: () => AuthedRoute,
    } as any,
  )
const AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute =
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRouteImport.update(
    {
      id: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId',
      path: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId',
      getParentRoute: () => AuthedRoute,
    } as any,
  )
const AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute =
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRouteImport.update(
    {
      id: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId',
      path: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId',
      getParentRoute: () => AuthedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/page': typeof AuthedPageRoute
  '/settings': typeof AuthedSettingsRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/clients/': typeof AuthedClientsIndexRoute
  '/library/': typeof AuthedLibraryIndexRoute
  '/library/exercises/new': typeof AuthedLibraryExercisesNewRoute
  '/library/foods/new': typeof AuthedLibraryFoodsNewRoute
  '/library/nutrition-plans/new': typeof AuthedLibraryNutritionPlansNewRoute
  '/library/recipes/new': typeof AuthedLibraryRecipesNewRoute
  '/library/training-plans/new': typeof AuthedLibraryTrainingPlansNewRoute
  '/login/verify': typeof GuestAuthLoginVerifyRoute
  '/register/verify': typeof GuestAuthRegisterVerifyRoute
  '/login/': typeof GuestAuthLoginIndexRoute
  '/register/': typeof GuestAuthRegisterIndexRoute
  '/library/exercises/$id/edit': typeof AuthedLibraryExercisesIdEditRoute
  '/library/foods/$id/edit': typeof AuthedLibraryFoodsIdEditRoute
  '/library/nutrition-plans/$id/edit': typeof AuthedLibraryNutritionPlansIdEditRoute
  '/library/recipes/$id/edit': typeof AuthedLibraryRecipesIdEditRoute
  '/library/training-plans/$id/edit': typeof AuthedLibraryTrainingPlansIdEditRoute
  '/library/nutrition-plans/$id/builder/': typeof AuthedLibraryNutritionPlansIdBuilderIndexRoute
  '/library/training-plans/$id/builder/': typeof AuthedLibraryTrainingPlansIdBuilderIndexRoute
  '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit': typeof AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/edit': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute
  '/library/nutrition-plans/$id/builder/days/$day/': typeof AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute
  '/library/training-plans/$id/builder/workouts/$workoutId/': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute
  '/library/nutrition-plans/$id/builder/days/$day/meals/new': typeof AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute
  '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute
  '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute
  '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/page': typeof AuthedPageRoute
  '/settings': typeof AuthedSettingsRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/library': typeof AuthedLibraryIndexRoute
  '/library/exercises/new': typeof AuthedLibraryExercisesNewRoute
  '/library/foods/new': typeof AuthedLibraryFoodsNewRoute
  '/library/nutrition-plans/new': typeof AuthedLibraryNutritionPlansNewRoute
  '/library/recipes/new': typeof AuthedLibraryRecipesNewRoute
  '/library/training-plans/new': typeof AuthedLibraryTrainingPlansNewRoute
  '/login/verify': typeof GuestAuthLoginVerifyRoute
  '/register/verify': typeof GuestAuthRegisterVerifyRoute
  '/login': typeof GuestAuthLoginIndexRoute
  '/register': typeof GuestAuthRegisterIndexRoute
  '/library/exercises/$id/edit': typeof AuthedLibraryExercisesIdEditRoute
  '/library/foods/$id/edit': typeof AuthedLibraryFoodsIdEditRoute
  '/library/nutrition-plans/$id/edit': typeof AuthedLibraryNutritionPlansIdEditRoute
  '/library/recipes/$id/edit': typeof AuthedLibraryRecipesIdEditRoute
  '/library/training-plans/$id/edit': typeof AuthedLibraryTrainingPlansIdEditRoute
  '/library/nutrition-plans/$id/builder': typeof AuthedLibraryNutritionPlansIdBuilderIndexRoute
  '/library/training-plans/$id/builder': typeof AuthedLibraryTrainingPlansIdBuilderIndexRoute
  '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit': typeof AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/edit': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute
  '/library/nutrition-plans/$id/builder/days/$day': typeof AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute
  '/library/training-plans/$id/builder/workouts/$workoutId': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute
  '/library/nutrition-plans/$id/builder/days/$day/meals/new': typeof AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute
  '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute
  '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/items/new': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute
  '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute
  '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/page': typeof AuthedPageRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_guest/_auth': typeof GuestAuthRouteWithChildren
  '/_authed/clients/$id': typeof AuthedClientsIdRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/library/': typeof AuthedLibraryIndexRoute
  '/_authed/library/exercises/new': typeof AuthedLibraryExercisesNewRoute
  '/_authed/library/foods/new': typeof AuthedLibraryFoodsNewRoute
  '/_authed/library/nutrition-plans/new': typeof AuthedLibraryNutritionPlansNewRoute
  '/_authed/library/recipes/new': typeof AuthedLibraryRecipesNewRoute
  '/_authed/library/training-plans/new': typeof AuthedLibraryTrainingPlansNewRoute
  '/_guest/_auth/login/verify': typeof GuestAuthLoginVerifyRoute
  '/_guest/_auth/register/verify': typeof GuestAuthRegisterVerifyRoute
  '/_guest/_auth/login/': typeof GuestAuthLoginIndexRoute
  '/_guest/_auth/register/': typeof GuestAuthRegisterIndexRoute
  '/_authed/library/exercises/$id/edit': typeof AuthedLibraryExercisesIdEditRoute
  '/_authed/library/foods/$id/edit': typeof AuthedLibraryFoodsIdEditRoute
  '/_authed/library/nutrition-plans/$id/edit': typeof AuthedLibraryNutritionPlansIdEditRoute
  '/_authed/library/recipes/$id/edit': typeof AuthedLibraryRecipesIdEditRoute
  '/_authed/library/training-plans/$id/edit': typeof AuthedLibraryTrainingPlansIdEditRoute
  '/_authed/library/nutrition-plans/$id/builder/': typeof AuthedLibraryNutritionPlansIdBuilderIndexRoute
  '/_authed/library/training-plans/$id/builder/': typeof AuthedLibraryTrainingPlansIdBuilderIndexRoute
  '/_authed/library/nutrition-plans/$id/builder/assignments/$planItemId/edit': typeof AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute
  '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/edit': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute
  '/_authed/library/nutrition-plans/$id/builder/days/$day/': typeof AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute
  '/_authed/library/training-plans/$id/builder/workouts/$workoutId/': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute
  '/_authed/library/nutrition-plans/$id/builder/days/$day/meals/new': typeof AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute
  '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute
  '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute
  '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute
  '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute
  '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/': typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute
  '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId': typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/page'
    | '/settings'
    | '/clients/$id'
    | '/clients/'
    | '/library/'
    | '/library/exercises/new'
    | '/library/foods/new'
    | '/library/nutrition-plans/new'
    | '/library/recipes/new'
    | '/library/training-plans/new'
    | '/login/verify'
    | '/register/verify'
    | '/login/'
    | '/register/'
    | '/library/exercises/$id/edit'
    | '/library/foods/$id/edit'
    | '/library/nutrition-plans/$id/edit'
    | '/library/recipes/$id/edit'
    | '/library/training-plans/$id/edit'
    | '/library/nutrition-plans/$id/builder/'
    | '/library/training-plans/$id/builder/'
    | '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/edit'
    | '/library/nutrition-plans/$id/builder/days/$day/'
    | '/library/training-plans/$id/builder/workouts/$workoutId/'
    | '/library/nutrition-plans/$id/builder/days/$day/meals/new'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId'
    | '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId'
    | '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/'
    | '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/page'
    | '/settings'
    | '/clients/$id'
    | '/clients'
    | '/library'
    | '/library/exercises/new'
    | '/library/foods/new'
    | '/library/nutrition-plans/new'
    | '/library/recipes/new'
    | '/library/training-plans/new'
    | '/login/verify'
    | '/register/verify'
    | '/login'
    | '/register'
    | '/library/exercises/$id/edit'
    | '/library/foods/$id/edit'
    | '/library/nutrition-plans/$id/edit'
    | '/library/recipes/$id/edit'
    | '/library/training-plans/$id/edit'
    | '/library/nutrition-plans/$id/builder'
    | '/library/training-plans/$id/builder'
    | '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/edit'
    | '/library/nutrition-plans/$id/builder/days/$day'
    | '/library/training-plans/$id/builder/workouts/$workoutId'
    | '/library/nutrition-plans/$id/builder/days/$day/meals/new'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId'
    | '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId'
    | '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/items/new'
    | '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new'
    | '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_guest'
    | '/_authed/onboarding'
    | '/_authed/page'
    | '/_authed/settings'
    | '/_guest/_auth'
    | '/_authed/clients/$id'
    | '/_authed/clients/'
    | '/_authed/library/'
    | '/_authed/library/exercises/new'
    | '/_authed/library/foods/new'
    | '/_authed/library/nutrition-plans/new'
    | '/_authed/library/recipes/new'
    | '/_authed/library/training-plans/new'
    | '/_guest/_auth/login/verify'
    | '/_guest/_auth/register/verify'
    | '/_guest/_auth/login/'
    | '/_guest/_auth/register/'
    | '/_authed/library/exercises/$id/edit'
    | '/_authed/library/foods/$id/edit'
    | '/_authed/library/nutrition-plans/$id/edit'
    | '/_authed/library/recipes/$id/edit'
    | '/_authed/library/training-plans/$id/edit'
    | '/_authed/library/nutrition-plans/$id/builder/'
    | '/_authed/library/training-plans/$id/builder/'
    | '/_authed/library/nutrition-plans/$id/builder/assignments/$planItemId/edit'
    | '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/edit'
    | '/_authed/library/nutrition-plans/$id/builder/days/$day/'
    | '/_authed/library/training-plans/$id/builder/workouts/$workoutId/'
    | '/_authed/library/nutrition-plans/$id/builder/days/$day/meals/new'
    | '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId'
    | '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId'
    | '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId'
    | '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/'
    | '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/'
    | '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/_auth': {
      id: '/_guest/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestAuthRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/page': {
      id: '/_authed/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof AuthedPageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/': {
      id: '/_authed/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthedLibraryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$id': {
      id: '/_authed/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthedClientsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/_auth/register/': {
      id: '/_guest/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof GuestAuthRegisterIndexRouteImport
      parentRoute: typeof GuestAuthRoute
    }
    '/_guest/_auth/login/': {
      id: '/_guest/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof GuestAuthLoginIndexRouteImport
      parentRoute: typeof GuestAuthRoute
    }
    '/_guest/_auth/register/verify': {
      id: '/_guest/_auth/register/verify'
      path: '/register/verify'
      fullPath: '/register/verify'
      preLoaderRoute: typeof GuestAuthRegisterVerifyRouteImport
      parentRoute: typeof GuestAuthRoute
    }
    '/_guest/_auth/login/verify': {
      id: '/_guest/_auth/login/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof GuestAuthLoginVerifyRouteImport
      parentRoute: typeof GuestAuthRoute
    }
    '/_authed/library/training-plans/new': {
      id: '/_authed/library/training-plans/new'
      path: '/library/training-plans/new'
      fullPath: '/library/training-plans/new'
      preLoaderRoute: typeof AuthedLibraryTrainingPlansNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/recipes/new': {
      id: '/_authed/library/recipes/new'
      path: '/library/recipes/new'
      fullPath: '/library/recipes/new'
      preLoaderRoute: typeof AuthedLibraryRecipesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/new': {
      id: '/_authed/library/nutrition-plans/new'
      path: '/library/nutrition-plans/new'
      fullPath: '/library/nutrition-plans/new'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/foods/new': {
      id: '/_authed/library/foods/new'
      path: '/library/foods/new'
      fullPath: '/library/foods/new'
      preLoaderRoute: typeof AuthedLibraryFoodsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/exercises/new': {
      id: '/_authed/library/exercises/new'
      path: '/library/exercises/new'
      fullPath: '/library/exercises/new'
      preLoaderRoute: typeof AuthedLibraryExercisesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/training-plans/$id/edit': {
      id: '/_authed/library/training-plans/$id/edit'
      path: '/library/training-plans/$id/edit'
      fullPath: '/library/training-plans/$id/edit'
      preLoaderRoute: typeof AuthedLibraryTrainingPlansIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/recipes/$id/edit': {
      id: '/_authed/library/recipes/$id/edit'
      path: '/library/recipes/$id/edit'
      fullPath: '/library/recipes/$id/edit'
      preLoaderRoute: typeof AuthedLibraryRecipesIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/edit': {
      id: '/_authed/library/nutrition-plans/$id/edit'
      path: '/library/nutrition-plans/$id/edit'
      fullPath: '/library/nutrition-plans/$id/edit'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/foods/$id/edit': {
      id: '/_authed/library/foods/$id/edit'
      path: '/library/foods/$id/edit'
      fullPath: '/library/foods/$id/edit'
      preLoaderRoute: typeof AuthedLibraryFoodsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/exercises/$id/edit': {
      id: '/_authed/library/exercises/$id/edit'
      path: '/library/exercises/$id/edit'
      fullPath: '/library/exercises/$id/edit'
      preLoaderRoute: typeof AuthedLibraryExercisesIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/training-plans/$id/builder/': {
      id: '/_authed/library/training-plans/$id/builder/'
      path: '/library/training-plans/$id/builder'
      fullPath: '/library/training-plans/$id/builder/'
      preLoaderRoute: typeof AuthedLibraryTrainingPlansIdBuilderIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/': {
      id: '/_authed/library/nutrition-plans/$id/builder/'
      path: '/library/nutrition-plans/$id/builder'
      fullPath: '/library/nutrition-plans/$id/builder/'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/training-plans/$id/builder/workouts/$workoutId/': {
      id: '/_authed/library/training-plans/$id/builder/workouts/$workoutId/'
      path: '/library/training-plans/$id/builder/workouts/$workoutId'
      fullPath: '/library/training-plans/$id/builder/workouts/$workoutId/'
      preLoaderRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/days/$day/': {
      id: '/_authed/library/nutrition-plans/$id/builder/days/$day/'
      path: '/library/nutrition-plans/$id/builder/days/$day'
      fullPath: '/library/nutrition-plans/$id/builder/days/$day/'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/edit': {
      id: '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/edit'
      path: '/library/nutrition-plans/$id/builder/meals/$mealId/edit'
      fullPath: '/library/nutrition-plans/$id/builder/meals/$mealId/edit'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/assignments/$planItemId/edit': {
      id: '/_authed/library/nutrition-plans/$id/builder/assignments/$planItemId/edit'
      path: '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit'
      fullPath: '/library/nutrition-plans/$id/builder/assignments/$planItemId/edit'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId': {
      id: '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId'
      path: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId'
      fullPath: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/$elementId'
      preLoaderRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId': {
      id: '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId'
      path: '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId'
      fullPath: '/library/nutrition-plans/$id/builder/meals/$mealId/items/$itemId'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/days/$day/meals/new': {
      id: '/_authed/library/nutrition-plans/$id/builder/days/$day/meals/new'
      path: '/library/nutrition-plans/$id/builder/days/$day/meals/new'
      fullPath: '/library/nutrition-plans/$id/builder/days/$day/meals/new'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/': {
      id: '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/'
      path: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new'
      fullPath: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/'
      preLoaderRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/': {
      id: '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/'
      path: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new'
      fullPath: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId': {
      id: '/_authed/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId'
      path: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId'
      fullPath: '/library/training-plans/$id/builder/workouts/$workoutId/exercises/new/$exerciseId'
      preLoaderRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId': {
      id: '/_authed/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId'
      path: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId'
      fullPath: '/library/nutrition-plans/$id/builder/meals/$mealId/items/new/$sourceType/$sourceId'
      preLoaderRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedPageRoute: typeof AuthedPageRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedClientsIdRoute: typeof AuthedClientsIdRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
  AuthedLibraryIndexRoute: typeof AuthedLibraryIndexRoute
  AuthedLibraryExercisesNewRoute: typeof AuthedLibraryExercisesNewRoute
  AuthedLibraryFoodsNewRoute: typeof AuthedLibraryFoodsNewRoute
  AuthedLibraryNutritionPlansNewRoute: typeof AuthedLibraryNutritionPlansNewRoute
  AuthedLibraryRecipesNewRoute: typeof AuthedLibraryRecipesNewRoute
  AuthedLibraryTrainingPlansNewRoute: typeof AuthedLibraryTrainingPlansNewRoute
  AuthedLibraryExercisesIdEditRoute: typeof AuthedLibraryExercisesIdEditRoute
  AuthedLibraryFoodsIdEditRoute: typeof AuthedLibraryFoodsIdEditRoute
  AuthedLibraryNutritionPlansIdEditRoute: typeof AuthedLibraryNutritionPlansIdEditRoute
  AuthedLibraryRecipesIdEditRoute: typeof AuthedLibraryRecipesIdEditRoute
  AuthedLibraryTrainingPlansIdEditRoute: typeof AuthedLibraryTrainingPlansIdEditRoute
  AuthedLibraryNutritionPlansIdBuilderIndexRoute: typeof AuthedLibraryNutritionPlansIdBuilderIndexRoute
  AuthedLibraryTrainingPlansIdBuilderIndexRoute: typeof AuthedLibraryTrainingPlansIdBuilderIndexRoute
  AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute: typeof AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute
  AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute: typeof AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute
  AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute: typeof AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute: typeof AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute: typeof AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedPageRoute: AuthedPageRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedClientsIdRoute: AuthedClientsIdRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
  AuthedLibraryIndexRoute: AuthedLibraryIndexRoute,
  AuthedLibraryExercisesNewRoute: AuthedLibraryExercisesNewRoute,
  AuthedLibraryFoodsNewRoute: AuthedLibraryFoodsNewRoute,
  AuthedLibraryNutritionPlansNewRoute: AuthedLibraryNutritionPlansNewRoute,
  AuthedLibraryRecipesNewRoute: AuthedLibraryRecipesNewRoute,
  AuthedLibraryTrainingPlansNewRoute: AuthedLibraryTrainingPlansNewRoute,
  AuthedLibraryExercisesIdEditRoute: AuthedLibraryExercisesIdEditRoute,
  AuthedLibraryFoodsIdEditRoute: AuthedLibraryFoodsIdEditRoute,
  AuthedLibraryNutritionPlansIdEditRoute:
    AuthedLibraryNutritionPlansIdEditRoute,
  AuthedLibraryRecipesIdEditRoute: AuthedLibraryRecipesIdEditRoute,
  AuthedLibraryTrainingPlansIdEditRoute: AuthedLibraryTrainingPlansIdEditRoute,
  AuthedLibraryNutritionPlansIdBuilderIndexRoute:
    AuthedLibraryNutritionPlansIdBuilderIndexRoute,
  AuthedLibraryTrainingPlansIdBuilderIndexRoute:
    AuthedLibraryTrainingPlansIdBuilderIndexRoute,
  AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute:
    AuthedLibraryNutritionPlansIdBuilderAssignmentsPlanItemIdEditRoute,
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute:
    AuthedLibraryNutritionPlansIdBuilderMealsMealIdEditRoute,
  AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute:
    AuthedLibraryNutritionPlansIdBuilderDaysDayIndexRoute,
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute:
    AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdIndexRoute,
  AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute:
    AuthedLibraryNutritionPlansIdBuilderDaysDayMealsNewRoute,
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute:
    AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsItemIdRoute,
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute:
    AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesElementIdRoute,
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute:
    AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewExerciseIdRoute,
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute:
    AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewIndexRoute,
  AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute:
    AuthedLibraryTrainingPlansIdBuilderWorkoutsWorkoutIdExercisesNewIndexRoute,
  AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute:
    AuthedLibraryNutritionPlansIdBuilderMealsMealIdItemsNewSourceTypeSourceIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestAuthRouteChildren {
  GuestAuthLoginVerifyRoute: typeof GuestAuthLoginVerifyRoute
  GuestAuthRegisterVerifyRoute: typeof GuestAuthRegisterVerifyRoute
  GuestAuthLoginIndexRoute: typeof GuestAuthLoginIndexRoute
  GuestAuthRegisterIndexRoute: typeof GuestAuthRegisterIndexRoute
}

const GuestAuthRouteChildren: GuestAuthRouteChildren = {
  GuestAuthLoginVerifyRoute: GuestAuthLoginVerifyRoute,
  GuestAuthRegisterVerifyRoute: GuestAuthRegisterVerifyRoute,
  GuestAuthLoginIndexRoute: GuestAuthLoginIndexRoute,
  GuestAuthRegisterIndexRoute: GuestAuthRegisterIndexRoute,
}

const GuestAuthRouteWithChildren = GuestAuthRoute._addFileChildren(
  GuestAuthRouteChildren,
)

interface GuestRouteChildren {
  GuestAuthRoute: typeof GuestAuthRouteWithChildren
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAuthRoute: GuestAuthRouteWithChildren,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
