export const JOINED_PROGRAMS = [
    // {
    //   id: 1,
    //   title: "Weight Loss Journey",
    //   coach: "Coach Sarah",
    //   progress: 65,
    //   daysLeft: 45,
    //   color: "blue",
    //   image: "💪",
    //   status: "Active",
    // },
    // {
    //   id: 2,
    //   title: "Strength Training",
    //   coach: "Coach Mike",
    //   progress: 30,
    //   daysLeft: 90,
    //   color: "green",
    //   image: "🏋️",
    //   status: "Active",
    // },
    // {
    //   id: 3,
    //   title: "Nutrition Plan",
    //   coach: "Coach Emma",
    //   progress: 80,
    //   daysLeft: 20,
    //   color: "orange",
    //   image: "🥗",
    //   status: "Almost Complete",
    // },
    // {
    //   id: 4,
    //   title: "Cardio Fitness",
    //   coach: "Coach Alex",
    //   progress: 15,
    //   daysLeft: 120,
    //   color: "purple",
    //   image: "🏃",
    //   status: "Just Started",
    // },
  ];