import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Nunito,
  Nunito_Sans,
  Funnel_Display,
  Inter,
  Intel_One_Mono,
} from "next/font/google";
import "./globals.css";

const nunitoSans = Inter({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const nunito = Intel_One_Mono({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} ${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
