export const ROUTES = {
  LOGIN: '/login',
  VERIFY_LOGIN_OTP: '/verify-login',
  ACCEPT_INVITE: '/invite/:token',
  VERIFY_INVITE_OTP: '/invite/:token/verify',
  TRAINING: '/',
  NUTRITION: '/nutrition',
  NUTRITION_HISTORY: '/nutrition/history',
  PROGRESS: '/progress',
  CHECKINS: '/check-ins',
  CHECKIN_FILL: '/check-ins/:id',
  WORKOUT_ACTIVE: '/workout',
  WORKOUT_HISTORY: '/history',
  SESSION_DETAIL: '/history/:sessionId',
  SETTINGS: '/settings',
} as const;
